### ISSUE TITLE
OrbLB disappeared

### ISSUE THREAD

**Issue by trquinn** [UIUC-PPL/charm#2620] opened 2019-11-23 05:16 UTC
ChaNGa no longer compiles because:
```
MultistepOrbLB.decl.h:7:10: fatal error: OrbLB.decl.h: No such file or directory
    7 | #include "OrbLB.decl.h"
```
I haven't tried this load balancer in a while, but it is still compiled in.

**Comment by hainest** [comment] 2019-11-25 03:24
#2527 is the cause.

**Comment by rbuch** [comment] 2019-12-01 08:22
Yes, `OrbLB` was removed in #2527 since it seemed like it was no longer in active use. If you all want it to continue supporting `MultistepOrbLB` in ChaNGa, we can add it back (or you all can ship it as part of ChaNGa; that may be preferable since it's not exactly a load balancer for all applications).

**Comment by rbuch** [comment] 2020-01-16 20:56
No longer an issue in ChaNGa since https://github.com/N-BodyShop/changa/pull/40 has been merged.

**Closed by rbuch** 2020-01-16 20:56 UTC
