### ISSUE TITLE
NAMD stmv run hangs on Cray XC30 (Cori) with gni-crayxc-persistent-smp build

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#2561] opened 2019-10-17 20:05 UTC
This bug was reported by Ted Packwood on the Charm mailing list. Still not sure if this is a bug in Charm++ or NAMD. 

Machine: Cori, Cray XC30

Loaded Modulelist:
```
nbhat4@cori09:~/software/charm> module list
Currently Loaded Modulefiles:
  1) modules/3.2.11.1
  2) nsg/1.2.0
  3) gcc/8.3.0
  4) craype-haswell
  5) craype-hugepages8M
  6) craype-network-aries
  7) craype/2.5.18
  8) cray-mpich/7.7.6
  9) python/2.7-anaconda-4.4
 10) gdb/8.3
 11) altd/2.0
 12) cray-libsci/19.02.1
 13) udreg/2.3.2-7.0.0.1_4.31__g8175d3d.ari
 14) ugni/6.0.14.0-7.0.0.1_7.35__ge78e5b0.ari
 15) pmi/5.0.14
 16) dmapp/7.1.1-7.0.0.1_5.29__g25e5077.ari
 17) gni-headers/5.0.12.0-7.0.0.1_7.46__g3b1768f.ari
 18) xpmem/2.2.17-7.0.0.1_3.28__g7acee3a.ari
 19) job/2.2.4-7.0.0.1_3.36__g36b56f4.ari
 20) dvs/2.11_2.2.140-7.0.0.1_13.5__gdf9ebba2
 21) alps/6.6.50-7.0.0.1_3.44__g962f7108.ari
 22) rca/2.2.20-7.0.0.1_4.42__g8e3fb5b.ari
 23) atp/2.1.3
 24) PrgEnv-gnu/6.0.5
 25) cray-fftw/3.3.8.3
 26) darshan/3.1.7
```

1. Build charm: (`v6.10.0-rc2`)
 `./build charm++ gni-crayxc persistent smp --build-shared -j16 -g -O0`

2. Build NAMD: (`c1eb46b3d79d0fd2ae6cb968a185a0f309743460`)
`./config CRAY-XC-gnu --charm-base /global/homes/n/nbhat4/software/charm --charm-arch gni-crayxc-persistent-smp --with-fftw3 --charm-opts -save`

3. Run Job with STMV input (https://www.ks.uiuc.edu/Research/namd/utilities/stmv.tar.gz)
Allocate Job with `salloc --qos=interactive -C haswell --time=60 --nodes=2 --ntasks-per-node=1 --cpus-per-task=2`
Run Job with `srun -n 2 -c 2 --ntasks-per-node 1 ./namd2 +p2 ../stmv/stmv.namd`

4. The hang shows up in the initial stages of the run:
```
nbhat4@nid00177:~/software/namd/CRAY-XC-gnu-with_tcl> srun -n 2 -c 2 --ntasks-per-node 1 ./namd2 +p2 ../stmv/stmv.namd
Charm++> Running on Gemini (GNI) with 2 processes
Charm++> static SMSG
Charm++> SMSG memory: 9.9KB
Charm++> memory pool init block size: 8MB, total memory pool limit 0MB (0 means no limit)
Charm++> memory pool registered memory limit: 200000MB, send limit: 100000MB
Charm++> only comm thread send/recv messages
Charm++> Cray TLB page size: 8192K
Charm++> Running in SMP mode: 2 processes, 2 worker threads (PEs) + 1 comm threads per process, 4 PEs total
Charm++> The comm. thread both sends and receives messages
Charm++> Using recursive bisection (scheme 3) for topology aware partitions
Converse/Charm++ Commit ID: v6.10.0-rc2-0-gcfec53c0a
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 2 hosts (2 sockets x 16 cores x 2 PUs = 64-way SMP)
Info: NAMD 2.13 for CRAY-XC-ugni-smp
Info:
Info: Please visit http://www.ks.uiuc.edu/Research/namd/
Info: for updates, documentation, and support information.
Info:
Info: Please cite Phillips et al., J. Comp. Chem. 26:1781-1802 (2005)
Info: in all publications reporting results obtained with NAMD.
Info:
Info: Based on Charm++/Converse 61000 for gni-crayxc-persistent-smp-ted-build-gnu
Info: Built Thu Oct 17 08:22:54 PDT 2019 by nbhat4 on cori09
Info: Running on 4 processors, 2 nodes, 2 physical nodes.
Info: CPU topology information available.
Info: Charm++/Converse parallel runtime startup completed at 0.00566167 s
CkLoopLib is used in SMP with simple dynamic scheduling (converse-level notification)
Info: 1358.43 MB of memory in use based on /proc/self/stat
Info: Configuration file is ../stmv/stmv.namd
Info: Changed directory to ../stmv
TCL: Suspending until startup complete.
Info: SIMULATION PARAMETERS:
Info: TIMESTEP               1
Info: NUMBER OF STEPS        500
Info: STEPS PER CYCLE        20
Info: PERIODIC CELL BASIS 1  216.832 0 0
Info: PERIODIC CELL BASIS 2  0 216.832 0
Info: PERIODIC CELL BASIS 3  0 0 216.832
Info: PERIODIC CELL CENTER   0 0 0
Info: LOAD BALANCER  Centralized
Info: LOAD BALANCING STRATEGY  New Load Balancers -- DEFAULT
Info: LDB PERIOD             4000 steps
Info: FIRST LDB TIMESTEP     100
Info: LAST LDB TIMESTEP     -1
Info: LDB BACKGROUND SCALING 1
Info: HOM BACKGROUND SCALING 1
Info: PME BACKGROUND SCALING 1
Info: MIN ATOMS PER PATCH    40
Info: INITIAL TEMPERATURE    298
Info: CENTER OF MASS MOVING INITIALLY? NO
Info: DIELECTRIC             1
Info: EXCLUDE                SCALED ONE-FOUR
Info: 1-4 ELECTROSTATICS SCALED BY 1
Info: MODIFIED 1-4 VDW PARAMETERS WILL BE USED
Info: NO DCD TRAJECTORY OUTPUT
Info: NO EXTENDED SYSTEM TRAJECTORY OUTPUT
Info: NO VELOCITY DCD OUTPUT
Info: NO FORCE DCD OUTPUT
Info: OUTPUT FILENAME        /usr/tmp/stmv-output
Info: BINARY OUTPUT FILES WILL BE USED
Info: NO RESTART FILE
Info: SWITCHING ACTIVE
Info: SWITCHING ON           10
Info: SWITCHING OFF          12
Info: PAIRLIST DISTANCE      13.5
Info: PAIRLIST SHRINK RATE   0.01
Info: PAIRLIST GROW RATE     0.01
Info: PAIRLIST TRIGGER       0.3
Info: PAIRLISTS PER CYCLE    2
Info: PAIRLISTS ENABLED
Info: MARGIN                 0.48
Info: HYDROGEN GROUP CUTOFF  2.5
Info: PATCH DIMENSION        16.48
Info: ENERGY OUTPUT STEPS    20
Info: CROSSTERM ENERGY INCLUDED IN DIHEDRAL
Info: TIMING OUTPUT STEPS    20
Info: LANGEVIN DYNAMICS ACTIVE
Info: LANGEVIN TEMPERATURE   298
Info: LANGEVIN USING BBK INTEGRATOR
Info: LANGEVIN DAMPING COEFFICIENT IS 5 INVERSE PS
Info: LANGEVIN DYNAMICS NOT APPLIED TO HYDROGENS
Info: LANGEVIN PISTON PRESSURE CONTROL ACTIVE
Info:        TARGET PRESSURE IS 1.01325 BAR
Info:     OSCILLATION PERIOD IS 100 FS
Info:             DECAY TIME IS 50 FS
Info:     PISTON TEMPERATURE IS 298 K
Info:       PRESSURE CONTROL IS GROUP-BASED
Info:    INITIAL STRAIN RATE IS 0 0 0
Info:       CELL FLUCTUATION IS ISOTROPIC
Info: PARTICLE MESH EWALD (PME) ACTIVE
Info: PME TOLERANCE               1e-06
Info: PME EWALD COEFFICIENT       0.257952
Info: PME INTERPOLATION ORDER     4
Info: PME GRID DIMENSIONS         216 216 216
Info: PME MAXIMUM GRID SPACING    1.5
Info: Attempting to read FFTW data from system
Info: Attempting to read FFTW data from FFTW_NAMD_2.13_CRAY-XC-ugni-smp_FFTW3.txt
Info: Optimizing 6 FFT steps.  1... 2... 3... 4... 5... 6...   Done.
Info: Writing FFTW data to FFTW_NAMD_2.13_CRAY-XC-ugni-smp_FFTW3.txt
Info: FULL ELECTROSTATIC EVALUATION FREQUENCY      4
Info: USING VERLET I (r-RESPA) MTS SCHEME.
Info: C1 SPLITTING OF LONG RANGE ELECTROSTATICS
Info: PLACING ATOMS IN PATCHES BY HYDROGEN GROUPS
Info: RANDOM NUMBER SEED     1571341865
Info: USE HYDROGEN BONDS?    NO
Info: COORDINATE PDB         stmv.pdb
Info: STRUCTURE FILE         stmv.psf
Info: PARAMETER file: CHARMM format!
Info: PARAMETERS             par_all27_prot_na.inp
Info: USING ARITHMETIC MEAN TO COMBINE L-J SIGMA PARAMETERS
Info: SUMMARY OF PARAMETERS:
Info: 250 BONDS
Info: 622 ANGLES
Info: 1049 DIHEDRAL
Info: 73 IMPROPER
Info: 0 CROSSTERM
Info: 130 VDW
Info: 0 VDW_PAIRS
Info: 0 NBTHOLE_PAIRS
Info: TIME FOR READING PSF FILE: 9.92055
Info: Reading pdb file stmv.pdb
Info: TIME FOR READING PDB FILE: 2.51474
Info:
Info: ****************************
Info: STRUCTURE SUMMARY:
Info: 1066628 ATOMS
Info: 769956 BONDS
Info: 605872 ANGLES
Info: 450875 DIHEDRALS
Info: 24578 IMPROPERS
Info: 0 CROSSTERMS
Info: 0 EXCLUSIONS
Info: 3199884 DEGREES OF FREEDOM
Info: 389067 HYDROGEN GROUPS
Info: 4 ATOMS IN LARGEST HYDROGEN GROUP
Info: 389067 MIGRATION GROUPS
Info: 4 ATOMS IN LARGEST MIGRATION GROUP
Info: TOTAL MASS = 6.69877e+06 amu
Info: TOTAL CHARGE = 0.000168104 e
Info: MASS DENSITY = 1.09115 g/cm^3
Info: ATOM DENSITY = 0.104627 atoms/A^3
Info: *****************************
Info:
Info: Entering startup at 12.5534 s, 1647.2 MB of memory in use
Info: Startup phase 0 took 0.00266009 s, 1647.2 MB of memory in use
Info: ADDED 1810196 IMPLICIT EXCLUSIONS
Info: Startup phase 1 took 0.737189 s, 1890.5 MB of memory in use
Info: NONBONDED TABLE R-SQUARED SPACING: 0.0625
Info: NONBONDED TABLE SIZE: 769 POINTS
Info: ABSOLUTE IMPRECISION IN FAST TABLE FORCE: 2.64698e-23 AT 11.9138
Info: RELATIVE IMPRECISION IN FAST TABLE FORCE: 1.40436e-16 AT 11.9138
Info: INCONSISTENCY IN FAST TABLE ENERGY VS FORCE: 0.000325096 AT 11.9556
Info: ABSOLUTE IMPRECISION IN SCOR TABLE FORCE: 4.10282e-22 AT 11.9138
Info: RELATIVE IMPRECISION IN SCOR TABLE FORCE: 3.56912e-15 AT 11.9138
Info: INCONSISTENCY IN SCOR TABLE ENERGY VS FORCE: 0.000324844 AT 11.9556
Info: ABSOLUTE IMPRECISION IN VDWA TABLE ENERGY: 9.86076e-32 AT 11.8295
Info: RELATIVE IMPRECISION IN VDWA TABLE ENERGY: 6.75473e-14 AT 11.9138
Info: ABSOLUTE IMPRECISION IN VDWA TABLE FORCE: 4.62223e-32 AT 11.9138
Info: RELATIVE IMPRECISION IN VDWA TABLE FORCE: 2.12237e-15 AT 11.9138
Info: INCONSISTENCY IN VDWA TABLE ENERGY VS FORCE: 0.0040507 AT 0.251946
Info: ABSOLUTE IMPRECISION IN VDWB TABLE ENERGY: 4.1359e-25 AT 11.8295
Info: RELATIVE IMPRECISION IN VDWB TABLE ENERGY: 7.56853e-15 AT 11.9138
Info: ABSOLUTE IMPRECISION IN VDWB TABLE FORCE: 3.87741e-26 AT 11.9138
Info: RELATIVE IMPRECISION IN VDWB TABLE FORCE: 5.97409e-16 AT 11.9138
Info: INCONSISTENCY IN VDWB TABLE ENERGY VS FORCE: 0.00150189 AT 0.251946
Info: Startup phase 2 took 0.00114155 s, 1890.5 MB of memory in use
Info: Startup phase 3 took 7.0946e-05 s, 1890.5 MB of memory in use
Info: Startup phase 4 took 0.00373355 s, 1890.5 MB of memory in use
Info: Startup phase 5 took 7.0967e-05 s, 1890.5 MB of memory in use
Info: PATCH GRID IS 13 (PERIODIC) BY 13 (PERIODIC) BY 13 (PERIODIC)
Info: PATCH GRID IS 1-AWAY BY 1-AWAY BY 1-AWAY
Info: REMOVING COM VELOCITY 0.00772212 0.00305349 -0.00947445
Info: LARGEST PATCH (1044) HAS 541 ATOMS
Info: TORUS A SIZE 2 USING 0 1
Info: TORUS B SIZE 1 USING 0
Info: TORUS C SIZE 1 USING 0
Info: TORUS MINIMAL MESH SIZE IS 2 BY 1 BY 1
Info: Placed 100% of base nodes on same physical node as patch
Info: Startup phase 6 took 0.322141 s, 2037.91 MB of memory in use
Info: PME using 4 and 4 processors for FFT and reciprocal sum.
Info: PME GRID LOCATIONS: 0 1 2 3
Info: PME TRANS LOCATIONS: 0 1 2 3
Info: PME USING 2 GRID NODES AND 2 TRANS NODES
Info: Optimizing 4 FFT steps.  1... 2... 3... 4...   Done.
Info: Startup phase 7 took 0.956112 s, 2057.57 MB of memory in use
Info: Startup phase 8 took 0.000101115 s, 2057.57 MB of memory in use
Info: Startup phase 9 took 0.0112508 s, 2057.57 MB of memory in use
Info: Startup phase 10 took 6.8524e-05 s, 2057.57 MB of memory in use
Info: Startup phase 11 took 0.0183849 s, 2057.57 MB of memory in use
LDB: Central LB being created...
Info: Startup phase 12 took 0.00486397 s, 2057.57 MB of memory in use
Info: CREATING 43960 COMPUTE OBJECTS
Info: Startup phase 13 took 0.0542812 s, 2121.57 MB of memory in use
Info: Building spanning tree ... send: 1 recv: 0 with branch factor 4
Info: useSync: 0 useProxySync: 0
Info: Startup phase 14 took 0.00106864 s, 2121.57 MB of memory in use
Info: Startup phase 15 took 0.0013279 s, 2134.57 MB of memory in use
Info: Finished startup at 14.6679 s, 2134.57 MB of memory in use

ETITLE:      TS           BOND          ANGLE          DIHED          IMPRP               ELECT            VDW       BOUNDARY           MISC        KINETIC               TOTAL           TEMP      POTENTIAL         TOTAL3        TEMPAVG            PRESSURE      GPRESSURE         VOLUME       PRESSAVG      GPRESSAVG

ENERGY:       0    354072.1600    280839.0161     81957.9556      4995.4407       -4503168.0872    384266.4685         0.0000         0.0000    948145.6670       -2448891.3793       298.2162  -3397037.0464  -2440252.1543       298.2162           1829.3220       188.2545  10194598.5131      1829.3220       188.2545
```

**Comment by rbuch** [comment] 2019-10-17 20:25
Note that `CRAY-XC-gnu` doesn't exist by default in current version of NAMD, but it's fairly trivial for uses to add that architecture by copying and slightly modifying existing files.

**Comment by ericjbohm** [comment] 2019-10-17 20:27
Worth learning more about how he built that architecture file as it might
differ in some subtle but important way from our attempts to reproduce it.

**Comment by jcphill** [comment] 2019-10-18 14:14
My money is on a bug in gcc, so you could try changing the gcc module or building NAMD with -g -O0 to see if it goes away.

What does CRAY-XC-gnu.arch contain?

Does the hang occur with both processes on the same host?

Does mpi-crayxc work?

**Comment by rbuch** [comment] 2019-10-18 14:26
> My money is on a bug in gcc, so you could try changing the gcc module or building NAMD with -g -O0 to see if it goes away.
> 
> What does CRAY-XC-gnu.arch contain?
> 
> Does the hang occur with both processes on the same host?
> 
> Does mpi-crayxc work?

It hangs with both gcc 8.3.0 and 9.1.0. It does not hang when NAMD is compiled with - O0 or - O1 with either of those two compilers, only - O2 and higher.

**Comment by jcphill** [comment] 2019-10-18 14:59
The default gcc on Cori seems to be 8.2.0. Where did you find 9.1.0?

**Comment by rbuch** [comment] 2019-10-18 15:26
> The default gcc on Cori seems to be 8.2.0. Where did you find 9.1.0?

Testing with 9.1.0 was done by Ted Packwood at Cray, presumably on some XC he has access to, not Cori.

**Comment by nitbhat** [comment] 2019-10-18 16:26
> My money is on a bug in gcc, so you could try changing the gcc module or building NAMD with -g -O0 to see if it goes away.

Yeah, I tried that (and so did Ted). The bug goes away with `-g -O0`.
I also tried the intel compilers and the bug didn't show up even then.   

> 
> What does CRAY-XC-gnu.arch contain?

Contents of `CRAY-XC-gnu.arch`:
```
NAMD_ARCH = CRAY-XC
CHARMARCH = gni-crayxc-persistent-smp
CXX = CC -std=c++11 -DNOHOSTNAME -DNO_GETPWUID
CXXOPTS = -O3 $(CRAY_UGNI_INCLUDE_OPTS)
CC = cc
COPTS = -O3 $(CRAY_UGNI_INCLUDE_OPTS)

#
# ensure that required modules are loaded
#
$(info $(NAMD_PLATFORM))

loaded_modules := $(subst :, ,$(LOADEDMODULES))

module := $(filter rca/%,$(loaded_modules))
ifeq (,$(module))
  $(error module rca is not loaded)
else
  $(info found module $(module))
endif

module := $(filter PrgEnv-gnu/%,$(loaded_modules))
ifeq (,$(module))
  $(error module PrgEnv-gnu is not loaded)
else
  $(info found module $(module))
endif
```

> 
> Does the hang occur with both processes on the same host?

I think it doesn't hang that often but hangs once in a while. 


> Does mpi-crayxc work?

Yes, when compiled with `gnu`, it hangs under the same conditions. I'm trying `mpi-crayxc` with Intel compilers now.

**Comment by jcphill** [comment] 2019-10-18 16:33
Adding the following to CRAY-XC-gnu.arch makes the hang go away for me:
CXXTHREADOPTS = -O0
So I'd guess the compiler and the user-level threads are conflicting somehow.

**Comment by nitbhat** [comment] 2019-10-18 16:48
Yeah, that's likely. 

I tried `mpi-crayxc` with Intel compilers and there wasn't a hang.

**Comment by jcphill** [comment] 2019-10-18 17:46
Switching from uFcontext to uJcontext or pthread (which should be bullet-proof) doesn't help, nor does switching to gcc 8.2.0.

**Comment by jcphill** [comment] 2019-10-18 17:49
Switching to gcc 7.3.0 for the threaded files fixes the problem.

**Comment by rbuch** [comment] 2019-10-18 18:01
Since evidence is pointing to this likely being a bug or incompatibility in gcc, we're not going to block the Charm++ release on this being fixed.

**Comment by jcphill** [comment] 2019-10-18 18:40
We've had other reports of gcc 8 not working.

**Comment by jcphill** [comment] 2019-10-18 19:48
It hangs even on a single process. It hangs with stmv but not apoa1.
If I comment out langevin and langevinPiston then stmv works too.
After some debugging, I see this is the problem I've seen before where Random::gaussian() is miscompiled such that the underlying integer generator isn't being advanced and just returns the same numbers, so it gets stuck in a while loop.

**Comment by evan-charmworks** [comment] 2019-10-18 20:50
Should we close this issue and move discussion to NAMD's issue tracker?

**Comment by jcphill** [comment] 2019-10-18 21:00
Go ahead and close it. I'll try to find a workaround.

**Closed** 2019-10-18 21:07 UTC
Labels: gni
