### ISSUE TITLE
liveViz with non-charmrun based arch layers throws an error related to reduction

### ISSUE THREAD

**Issue by nitbhat** [UIUC-PPL/charm#2662] opened 2019-12-19 15:49 UTC
I was stung by this bug when I tried running a liveViz application with an mpi build. I see the following error message when trying to run a liveViz application (like wave2d) with an mpi build. 

```
MacBook-Pro-37:wave2d nitinbhat$ ./runserver.sh
Starting up server:

Running on 4 processors:  ./wave2d ++server ++server-port 1234
charmrun> mpirun -np 4  ./wave2d ++server ++server-port 1234
Charm++> Running on MPI version: 3.1
Charm++> level of thread support used: MPI_THREAD_SINGLE (desired: MPI_THREAD_SINGLE)
Charm++> Running in non-SMP mode: 4 processes (PEs)
Converse/Charm++ Commit ID: v6.10.0-rc2-21-ga10bae6
ccs: 2
ccs: Server IP = 10.24.111.12, Server port = 1234 $
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (1 sockets x 4 cores x 2 PUs = 8-way SMP)
Charm++> cpu topology info is gathered in 0.001 seconds.
Running wave2d on 4 processors
Mismatched callback details: reducers (CkReduction::sum_int, CkReduction::sum_int); callback types (CkCallback::call1Fn, CkCallback::call1Fn)
[0] Stack Traceback:
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: mis-matched client callbacks in reduction messages

  [0:0] wave2d 0x103faf431 CmiAbort
  [0:1] wave2d 0x103f4ef12 CkReductionMgr::reduceMessages(CkMsgQ<CkReductionMsg>&)
  [0:2] wave2d 0x103f4c77a CkReductionMgr::finishReduction()
  [0:3] wave2d 0x103ee6ab5 CkDeliverMessageFree
  [0:4] wave2d 0x103ee928f _processHandler(void*, CkCoreState*)
  [0:5] wave2d 0x103fb430c CsdScheduleForever
  [0:6] wave2d 0x103fb4125 CsdScheduler
  [0:7] wave2d 0x103fb0f0a ConverseInit
  [0:8] wave2d 0x103edc63e charm_main
  [0:9] wave2d 0x103ec0134 start
application called MPI_Abort(comm=0x84000004, 1) - process 0
Server Exited
```

The fix should involve throwing a more meaningful error until we get ccs tools working with other launchers (like mpirun, srun etc). The error message should prompt the user to run the application on of the charmrun based layers (like netlrts, where liveViz is known to work correctly).

**Comment by evan-charmworks** [comment] 2019-12-19 22:21
I believe the error you're seeing is related to ASLR, as an artifact of how mpirun launches processes. See #2018. What happens if you pass ++debug-no-pause to the charmrun shell script? GDB should disable ASLR by default.

As for liveViz, while I suspect the code itself will run with all machine layers, I don't think they have any way to send the content to the Java client. That functionality, including the `++server ++server-port 1234` parameters, is implemented by the netlrts/verbs charmrun.

**Comment by evan-charmworks** [comment] 2020-02-24 21:54
Duplicate of #2018

**Closed by evan-charmworks** 2020-02-24 21:54 UTC

**Comment by evan-charmworks** [comment] 2020-02-25 04:20
#2731 fixes liveViz to avoid the problematic function pointer construct that causes the problem.
