### ISSUE TITLE
RotateLB hangs with v6.11.0-beta1

### ISSUE THREAD

**Issue by jobordner** [UIUC-PPL/charm#3108] opened 2020-10-16 20:23 UTC
The Enzo-E load-balancing regression test hangs when RotateLB is used.  Some observations:

- works fine for +p2 and +p3: no hangs within the 10 balancing steps performed
- +p4 runs hang when calling the balancer for the 4th time
- +p4 hanging on the 4th attempt is repeatable
- hanging behavior does not occur in charm-6.10.2
- no other load balancers tested hung

**Comment by rbuch** [comment] 2020-10-16 20:29
Thanks for the report. Can you provide build information and the command line you used to execute so I can reproduce this?

**Comment by jobordner** [comment] 2020-10-16 20:54
This is using the `solver-dd` branch of https://github.com/jobordner/enzo-e.git run using "`charmrun +p4 bin/enzo-p input/load-balance-4.in +balancer RotateLB`"  I just tried the master branch of the main repository https://github.com/enzo-project/enzo-e.git and that worked fine.  Charm was built using `./build charm++ netlrts-linux-x86_64   -j4  --with-production --enable-tracing`.

**Comment by rbuch** [comment] 2020-10-22 19:22
I've been able to reproduce this, I'm currently trying to get to the bottom of what's going on. It seems like load balancing finishes when the hang happens, objects get their `ResumeFromSync` functions called, so it might be an issue in Enzo-E.

One question, it seems like the number of `Block` chares increases with every load balancing period, I assume this is expected because of refinement?

**Comment by rbuch** [comment] 2020-11-12 02:21
Using the `+LBSyncResume` flag seems to solve this in my tests, so I think there's some kind of object registration / calling `AtSync` race that's happening here.

**Comment by rbuch** [comment] 2021-05-18 23:58
Should be fixed in #3286.

**Closed by rbuch** 2021-05-18 23:58 UTC
Labels: Bug, load balancing
