### ISSUE TITLE
examples/ampi/cuda/simple segfaults

### ISSUE THREAD

**Issue by evan-charmworks** [UIUC-PPL/charm#2074] opened 2019-05-03 18:58 UTC
```gdb
(cuda-gdb) r
Starting program: ~/charm/netlrts-linux-x86_64-cuda/examples/ampi/cuda/simple/simple +vp1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Charm++: standalone mode (not using charmrun)
Charm++> Running in non-SMP mode: 1 processes (PEs)
Converse/Charm++ Commit ID: v6.9.0-279-g8e590121b
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (1 sockets x 6 cores x 2 PUs = 12-way SMP)
Charm++> cpu topology info is gathered in 0.016 seconds.
[New Thread 0x7fffef09c700 (LWP 21029)]
Calling kernel...
[New Thread 0x7fffee89b700 (LWP 21030)]
[New Thread 0x7fffee09a700 (LWP 21031)]

Thread 1 "simple" received signal SIGSEGV, Segmentation fault.
0x00007ffff54c8eda in cuEGLApiInit () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
(cuda-gdb) thread apply all bt

Thread 4 (Thread 0x7fffee09a700 (LWP 21031)):
#0  0x00007ffff6804f85 in futex_abstimed_wait_cancelable (private=<optimized out>, abstime=0x7fffee099e30, expected=0, futex_word=0x7fffcc000b48) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  __pthread_cond_wait_common (abstime=0x7fffee099e30, mutex=0x555555cd21a8, cond=0x7fffcc000b20) at pthread_cond_wait.c:539
#2  __pthread_cond_timedwait (cond=0x7fffcc000b20, mutex=0x555555cd21a8, abstime=0x7fffee099e30) at pthread_cond_wait.c:667
#3  0x00007ffff54fb5e7 in cuEGLApiInit () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007ffff54a40e7 in cudbgApiDetach () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007ffff54fa868 in cuEGLApiInit () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007ffff67fe6db in start_thread (arg=0x7fffee09a700) at pthread_create.c:463
#7  0x00007ffff6d3b88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fffee89b700 (LWP 21030)):
#0  0x00007ffff6d2ebf9 in __GI___poll (fds=0x7fffe0000c30, nfds=12, timeout=10) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007ffff54f8213 in cuEGLApiInit () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007ffff555a9cd in cuVDPAUCtxCreate () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007ffff54fa868 in cuEGLApiInit () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007ffff67fe6db in start_thread (arg=0x7fffee89b700) at pthread_create.c:463
#5  0x00007ffff6d3b88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fffef09c700 (LWP 21029)):
#0  0x00007ffff6d3d237 in accept4 (fd=13, addr=..., addr_len=0x7fffef09bdf8, flags=524288) at ../sysdeps/unix/sysv/linux/accept4.c:32
#1  0x00007ffff54f91aa in cuEGLApiInit () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007ffff54eb84d in cuEGLApiInit () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007ffff54fa868 in cuEGLApiInit () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007ffff67fe6db in start_thread (arg=0x7fffef09c700) at pthread_create.c:463
#5  0x00007ffff6d3b88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff7fc9340 (LWP 21018)):
#0  0x00007ffff54c8eda in cuEGLApiInit () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#1  0x00007ffff54e3644 in cuEGLApiInit () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007ffff53e0da4 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007ffff53e0f9e in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007ffff553873d in cuLaunchKernel () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007ffff7b7cf70 in __cudaInitModule () from /usr/lib/x86_64-linux-gnu/libcudart.so.9.1
#6  0x00007ffff7b9b7be in cudaLaunch () from /usr/lib/x86_64-linux-gnu/libcudart.so.9.1
#7  0x0000555555740a4d in cudaLaunch<char> (func=0x555555740985 <helloKernel()> "UH\211\345\350\326\377\377\377\220]\303UH\211\345H\203\354\020H\211}\370H\213E\370H\211\005\020\377P") at /usr/include/cuda_runtime.h:1879
#8  0x0000555555740982 in __device_stub__Z11helloKernelv () at /tmp/tmpxft_0000518c_00000000-5_simple-cuda.cudafe1.stub.c:10
#9  0x000055555574098e in helloKernel () at simple-cuda.cu:4
#10 0x00005555557408fb in invokeKernel (stream=0x7fffffffe2c8) at simple-cuda.cu:28
#11 0x0000555555740828 in AMPI_Main_cpp (argc=1, argv=0x555555c74f10) at simple.C:25
#12 0x0000555555754999 in AMPI_Fallback_Main (argc=1, argv=0x555555c74f10) at ampi.C:829
#13 0x0000555555798c84 in MPI_threadstart_t::start (this=0x401103f68) at ampi.C:1055
#14 0x0000555555754f27 in AMPI_threadstart (data=0x555555d27080) at ampi.C:1075
#15 0x00005555557412a8 in startTCharmThread (msg=0x555555d27060) at tcharm.C:163
#16 0x00005555558dae59 in CthStartThread (arg=...) at threads.C:1783
#17 0x00005555558db33f in make_fcontext ()
#18 0x0000000000000000 in ?? ()
```

**Comment by evan-charmworks** [comment] 2019-06-14 16:25
In separate testing, #2305 allows the example to work properly. Assigning this to Eric B since I have only reproduced this segfault on his workstation.

**Comment by minitu** [comment] 2020-07-21 22:21
Closing this issue for now, please reopen if the issue is not fixed.

**Closed by minitu** 2020-07-21 22:21 UTC
Labels: AMPI, Bug, GPU support
